### PR TITLE
Size table on mount, not after data load

### PR DESCRIPTION
**Pull request by HebaruSan**
## Problem

The [status page](http://status.ksp-ckan.space/) looks like this for a noticeable amount of time after load:

image

## Cause

The dimensions are set by `this._updateTableSize()`, via the `sucess` branch of `loadNetKANsFromServer()`. This means that while the netkans are being loaded, the table has its default size of 200px x 500px.

## Changes

Apparently `componentDidMount()` is the place to do UI updates like this at load. Now we do that, and it seems to provide instant sizing.

I'll probably self-review this so I can see whether it works in production.

### CODE REVIEW

**Comment by HebaruSan** [comment]
NPM :vomiting_face: :bomb: :rage:

**Comment by DasSkelett** [comment]
We should probably commit `package-lock.json` if we don't want dependencies to change unexpectedly

**Comment by HebaruSan** [comment]
I _want_ dependencies to change unexpectedly! Getting fixes automatically is the point of using a package manager!

**Comment by HebaruSan** [comment]
And `package.json`'s syntax should be sufficient! It already has various levels of matching, exact, approximate, etc.! There was no need to add to that!

**Comment by HebaruSan** [comment]
I give up. I wanted to fix the status page, not fight with NPM for hours and hours.
Feel free to re-open if you can fix this crap.

**Comment by DasSkelett** [comment]
>  npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or **--legacy-peer-deps**
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

If I do this (`npm install --legacy-peer-deps`), it installs, builds and runs just fine.

**Comment by HebaruSan** [comment]
Thanks! I guess that's OK since we are using a `package.json` from a long time ago.

**Comment by DasSkelett** [comment]
I mean it's still only a workaround, but yeah, npm's handling of so-called [peer dependencies](https://nodejs.org/en/blog/npm/peer-dependencies/) apparently changed in the meantime.
if you look at the [package.json of file-loader](https://github.com/webpack-contrib/file-loader/blame/master/package.json#L41), it had the requirement of `"webpack": "^4.0.0 || ^5.0.0"` (or `^4.0.0` before that) since a very long time, but npm just ignored that until now.

So technically the versions of `file-loader` and `webpack` we use are incompatible with each other, according to metadata, but they seem to work good enough for our little use.

**Pull request merged**
