### PR TITLE
Display and color code warnings

### PR DESCRIPTION
**Pull request by HebaruSan**
## Motivation

See KSP-CKAN/NetKAN-Infra#160 and KSP-CKAN/CKAN#3045 and KSP-CKAN/NetKAN-Infra#166; we may soon have non-fatal warnings in the status db, which can be used to improve metadata but are not showstoppers.

## Changes

Now the Error column is renamed Error / Warnings, and it falls back to showing the `last_warnings` status attribute if `last_error` is null.

To help differentiate warnings and errors visually, the color coding is back, with errors in red and warnings in yellow, which I have tried to make more pale in dark mode and darker in light mode to ensure they are easy to read:

image

image

(Note that these screenshots illustrate the colors only, since we do not currently have real warning text for testing.)

Fixes KSP-CKAN/NetKAN-Infra#160.

## Testing setup

1. Temporarily edit `src/javascript/app.jsx` to change `http://status.ksp-ckan.space/status/netkan.json` to `netkan.json`
2. `npm install`
3. `npm run build && ( cd dist; rm netkan.json; wget http://status.ksp-ckan.space/status/netkan.json && python3 -m http.server 5000 )`
4. Open in browser: http://127.0.0.1:5000/

### CODE REVIEW

**Comment by techman83** [comment]
My only comment here is that it may not be super colour blind friendly. We probably want to clearly label when somethings a Warning vs Error. I think it's ok that they're in the same column, maybe errors should be bold, warnings italic, along with the colours?

**Comment by HebaruSan** [comment]
What about icons?
:warning: - warning
:stop_sign: - error

**Comment by techman83** [comment]
Ooo. Yeah icons would be much clearer. With it in the title.

:warning: Warnings / :stop_sign: Errors

**Comment by HebaruSan** [comment]
OK, added some icons that are listed as "Freeware" here:

- https://findicons.com/icon/83791/onebit_35
- https://findicons.com/icon/83831/onebit_36

Screenshots updated in OP.

**Comment by techman83** [comment]
Might be worth using the google material icons, they have an open source license and we can tweak the colours as needed. We're likely ok licensing wise, but they don't link to the "Freeware" license and what it means.

https://google.github.io/material-design-icons/

https://www.tutlane.com/example/font-icons/change-material-design-icon-color-example

We can also NPM install them, so they don't need to be put into the source code. That aside, this looks really good.

**Comment by HebaruSan** [comment]
> Might be worth using the google material icons

I can't get them to work; page won't render if I import them. How important is this?

**Comment by techman83** [comment]
I'm not going to hold this back based on a nitpick, but lets maybe add a note somewhere to look at an improvement. This is sort of an internal status page, so I think we're ok here. If we were to include freeware assets in the main CKAN app distributed to users I think we'd want to take a harder line on it.

**Comment by HebaruSan** [comment]
I think I finally found the web site of the creator of those icons!

- http://www.sutasu.com/

The alert triangle is in this collection:

image

"Freeware" may be wrong; the preview and purchase button goes to a page where you can pay him $18 for a commercial license:

image

It may be that he just uploaded them to this creativemarket.com hoping to make a few bucks, but that doesn't do much to support the idea that he intended to give them away.

I will look for alternatives...

**Comment by HebaruSan** [comment]
OK, since I could not get the Material stuff to work as a Javascript import, I downloaded the error and warning icons as PNGs and colorized them in GIMP. Screenshots in OP updated.

**Comment by techman83** [comment]
Yeah, that was what I was wondering about about. I think that's an acceptable move for this sort of project, we can always look into that further later.

**Pull request merged**
